### ISSUE TITLE
ModuleNotFoundError: No module named 'damo'

### ISSUE THREAD

**Issue by yutao007** [tinyvision/DAMO-YOLO#11]
请大神帮忙看看，我这个问题确实有蒙蔽，在pycharm上都能正常导入引用，但是训练时候就会报错。
python -m torch.distributed.launch --nproc_per_node=1 tools/train.py -f configs/damoyolo_tinynasL20_T_fire_smoke_xy_calling_body.py 
/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from damo.apis import Trainer
ModuleNotFoundError: No module named 'damo'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 46733) of binary: /media/extend/anaconda3/envs/yolov5_2.0/bin/python
Traceback (most recent call last):
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-01_17:44:43
  host      : bova
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 46733)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by yutao007** [comment]
去掉 多余跑单机也是这个错误
python  tools/train.py -f configs/damoyolo_tinynasL20_T_fire_smoke_xy_calling_body.py 
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from damo.apis import Trainer
ModuleNotFoundError: No module named 'damo'

**Comment by yutao007** [comment]
添加完路径后出现分布式问题，我是单卡测试。请问有yolov5版模块吗？方便部署运行
export PYTHONPATH=/media/extend/DAMO-YOLO
(yolov5_2.0) :/media/extend/DAMO-YOLO$ python  tools/train.py -f configs/damoyolo_tinynasL20_T_fire_smoke_xy_calling_body.py 
2022-12-02 09:42:50.622 | ERROR    | __main__:<module>:67 - An error has been caught in function '<module>', process 'MainProcess' (54751), thread 'MainThread' (140447848367936):
Traceback (most recent call last):

> File "tools/train.py", line 67, in <module>
    main()
    └ <function main at 0x7fbc23326c10>

  File "tools/train.py", line 51, in main
    torch.distributed.init_process_group(backend='nccl', init_method='env://')
    │     │           └ <function init_process_group at 0x7fbc25e17790>
    │     └ <module 'torch.distributed' from '/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/...
    └ <module 'torch' from '/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/__init__.py'>

  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 576, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
    │      │                       └ <generator object _env_rendezvous_handler at 0x7fbc186017b0>
    │      └ -1
    └ None
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 219, in _env_rendezvous_handler
    rank = int(_get_env_or_raise("RANK"))
               └ <function _env_rendezvous_handler.<locals>._get_env_or_raise at 0x7fbc185d0160>
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 203, in _get_env_or_raise
    raise _env_error(env_var)
          │          └ 'RANK'
          └ <function _env_rendezvous_handler.<locals>._env_error at 0x7fbc185d01f0>

ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

**Comment by jyqi** [comment]
需要指定torch分布式以及nproc_per_node，尝试以下命令进行训练：
python -m torch.distributed.launch --nproc_per_node=1 tools/train.py -f configs/damoyolo_tinynasL20_T_fire_smoke_xy_calling_body.py

**Comment by funnymean** [comment]
> 执行export PYTHONPATH=当前项目路径，试试是否能够成功运行。

worked for me!
Thanks!

**Comment by yutao007** [comment]
谢谢，我发现是torch版本问题。目前来看torch1.7.0会正常到下一步，不过接着又出现空标背景图片读取问题，真是一部一坑阿，求大神指点。报错如下：
2022-12-03 15:37:13 | INFO     | damo.apis.detector_trainer:149 - Start Training...
2022-12-03 15:37:13 | INFO     | damo.apis.detector_trainer:152 - Enable ema model! Ema model will be evaluated and saved.
data_dir:/home/Documents/data_yu   attrs:{'img_dir': 'fire_smoke_xy_calling_body_coco/images/20221118/train2014', 'ann_file': 'fire_smoke_xy_calling_body_coco/annotations/instances_train2014.json'}
2022-12-03 15:37:13 | INFO     | torchvision.datasets.coco:113 - loading annotations into memory...
2022-12-03 15:37:13 | INFO     | torchvision.datasets.coco:113 - Done (t=0.24s)
2022-12-03 15:37:13 | INFO     | pycocotools.coco:89 - creating index...
2022-12-03 15:37:13 | INFO     | pycocotools.coco:89 - index created!
data_dir:/home/Documents/data_yu   attrs:{'img_dir': 'fire_smoke_xy_calling_body_coco/images/20221118/val2014', 'ann_file': 'fire_smoke_xy_calling_body_coco/annotations/instances_val2014.json'}
2022-12-03 15:37:13 | INFO     | torchvision.datasets.coco:113 - loading annotations into memory...
2022-12-03 15:37:14 | INFO     | torchvision.datasets.coco:113 - Done (t=0.02s)
2022-12-03 15:37:14 | INFO     | pycocotools.coco:89 - creating index...
2022-12-03 15:37:14 | INFO     | pycocotools.coco:89 - index created!
2022-12-03 15:37:22 | INFO     | damo.apis.detector_trainer:260 - Model Summary: backbone's params(M): 2.36, flops(G): 8.66, latency(ms): 7.389
neck's params(M): 5.92, flops(G): 8.53, latency(ms): 8.019
head's params(M): 0.60, flops(G): 1.92, latency(ms): 1.636
total latency(ms): 15.685, total flops(G): 19.11

2022-12-03 15:37:22 | INFO     | damo.apis.detector_trainer:266 - Training start...
2022-12-03 15:37:22 | ERROR    | __main__:67 - An error has been caught in function '<module>', process 'MainProcess' (62878), thread 'MainThread' (139690254944064):
Traceback (most recent call last):

> File "tools/train.py", line 67, in <module>
    main()
    └ <function main at 0x7f0bcff579d0>

  File "tools/train.py", line 63, in main
    trainer.train(args.local_rank)
    │       │     │    └ 0
    │       │     └ Namespace(config_file='configs/damoyolo_tinynasL20_T_fire_smoke_xy_calling_body.py', local_rank=0, opts=[], tea_ckpt=None, te...
    │       └ <function Trainer.train at 0x7f0bc66a6790>
    └ <damo.apis.detector_trainer.Trainer object at 0x7f0c2befba60>

  File "/media/extend/DAMO-YOLO/damo/apis/detector_trainer.py", line 272, in train
    for data_iter, (inps, targets, ids) in enumerate(self.train_loader):
                                                     │    └ <torch.utils.data.dataloader.DataLoader object at 0x7f0b8d1f4880>
                                                     └ <damo.apis.detector_trainer.Trainer object at 0x7f0c2befba60>

  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f0bcff3e1f0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f0bbc2bc550>
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f0b84e593a0>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f0bcff3e310>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f0bbc2bc550>
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7f0c2bc14dc0>
    └ <torch._utils.ExceptionWrapper object at 0x7f0b84e593a0>
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught ValueError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/media/bova/extend/a...
          │    └ <class 'ValueError'>
          └ <torch._utils.ExceptionWrapper object at 0x7f0b84e593a0>
ValueError: Caught ValueError in DataLoader worker process 0.

Original Traceback (most recent call last):
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/extend/DAMO-YOLO/damo/dataset/datasets/mosaic_wrapper.py", line 300, in __getitem__
    img, labels = random_affine(
  File "/media/extend/DAMO-YOLO/damo/dataset/datasets/mosaic_wrapper.py", line 142, in random_affine
    segments = resample_segments(segments)  # upsample
  File "/media/extend/DAMO-YOLO/damo/dataset/datasets/mosaic_wrapper.py", line 28, in resample_segments
    segments[i] = np.concatenate([
  File "/media/extend/DAMO-YOLO/damo/dataset/datasets/mosaic_wrapper.py", line 29, in <listcomp>
    np.interp(x, xp, s[:, i]) for i in range(2)
  File "<__array_function__ internals>", line 180, in interp
  File "/media/extend/anaconda3/envs/yolov5_2.0/lib/python3.8/site-packages/numpy/lib/function_base.py", line 1570, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty

**Comment by gf-zhong** [comment]
?

**Comment by gf-zhong** [comment]
My GPU is NVIDIA 3090, and this version of CUDA must be greater than 11.0. So I cannot install and use Torch1.7.0.How can I solve this problem
