### ISSUE TITLE
What is Problem? [Bug]: Traceback (most recent call last):   File "train.py", line 9, in <module>     from damo.apis import Trainer ModuleNotFoundError: No module named 'damo.apis'

### ISSUE THREAD

**Issue by Picrew** [tinyvision/DAMO-YOLO#114]
### Before Reporting

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully and no error occured during the installation process. (Otherwise, we recommand that you can ask a question using the Question template) 我已经仔细阅读了README上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar bugs. 我已经在[issue列表](https://github.com/tinyvision/DAMO-YOLO/issues)中搜索但是没有发现类似的bug报告。

### OS

ubuntu

### Device

2080ti

### CUDA version

11.3

### TensorRT version

no

### Python version

3.8

### PyTorch version

1.12

### torchvision version

配套

### Describe the bug

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from damo.apis import Trainer
ModuleNotFoundError: No module named 'damo.apis'

### To Reproduce

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from damo.apis import Trainer
ModuleNotFoundError: No module named 'damo.apis'

### Hyper-parameters/Configs

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from damo.apis import Trainer
ModuleNotFoundError: No module named 'damo.apis'

### Logs

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from damo.apis import Trainer
ModuleNotFoundError: No module named 'damo.apis'

### Screenshots

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from damo.apis import Trainer
ModuleNotFoundError: No module named 'damo.apis'

### Additional

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from damo.apis import Trainer
ModuleNotFoundError: No module named 'damo.apis'

**Comment by yanrihong** [comment]
have u solved that? i have the same problem

**Comment by mellow-75** [comment]
@yanrihong  did you find any solution to it ?? i am having the same problem

**Comment by LiaoZihZrong** [comment]
use  `export PYTHONPATH=`current_project_path' 
and see if it can run successfully.
