### ISSUE TITLE
win10安装报错

### ISSUE THREAD

**Issue by futureflsl** [tinyvision/DAMO-YOLO#13]
测试环境：
win10 x64 
VS2019
cuda11.1+cudnn8.2
torch==1.9.0+cu111
torchvision==0.10.0+cu111

执行python setupy.py install 报错

C:\Users\fut\Desktop\DAMO-YOLO-20221202>python setup.py install
running install
running bdist_egg
running egg_info
writing damo.egg-info\PKG-INFO
writing dependency_links to damo.egg-info\dependency_links.txt
writing top-level names to damo.egg-info\top_level.txt
reading manifest file 'damo.egg-info\SOURCES.txt'
writing manifest file 'damo.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'damo._C' extension
Emitting ninja build file C:\Users\fut\Desktop\DAMO-YOLO-20221202\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: 'C:/Users/fut/Desktop/DAMO-YOLO-20221202/damo/layers/csrc/vision.cpp', needed by 'C:/Users/fut/Desktop/DAMO-YOLO-20221202/build/temp.win-amd64-3.8/Release/Users/fut/Desktop/DAMO-YOLO-20221202/damo/layers/csrc/vision.obj', missing and no known rule to make it
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "D:\anaconda3\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    setuptools.setup(
  File "D:\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "D:\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "D:\anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\anaconda3\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 626, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by futureflsl** [comment]
解决了，不用python setup.py install.在推理脚本中sys.path把目录加入环境变量
