### ISSUE TITLE
运行出现bug 这么解决

### ISSUE THREAD

**Issue by sharp-xiang** [tinyvision/DAMO-YOLO#133]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

[Bug]: TypeError: Caught TypeError in DataLoader worker process 0. Original Traceback (most recent call last):   File "/data/Disk_B/minrui/anaconda3/envs/mmdetection/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop     data = fetcher.fetch(index)   File "/data/Disk_B/minrui/anaconda3/envs/mmdetection/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch     data = [self.dataset[idx] for idx in possibly_batched_index]   File "/data/Disk_B/minrui/anaconda3/envs/mmdetection/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>     data = [self.dataset[idx] for idx in possibly_batched_index]   File "/data/Disk_B/minrui/DAMO-YOLO-master/damo/dataset/datasets/mosaic_wrapper.py", line 226, in __getitem__     img, labels, segments, img_id = self._dataset.pull_item(idx)   File "/data/Disk_B/minrui/DAMO-YOLO-master/damo/dataset/datasets/coco.py", line 97, in pull_item     obj_mask += mask TypeError: 'int' object is not iterable

### Additional

![image](https://github.com/tinyvision/DAMO-YOLO/assets/84016975/d7522238-a2b7-49ef-b816-74cc29b13d7a)

**Comment by ksv87** [comment]
make sure that the files are instances_train 2017.json and instances_val2017.json segmentation tags are set to [] (not int) or fix the code here:
https://github.com/tinyvision/DAMO-YOLO/blob/319572eef367340267ab6ab8ae253527a71d7c3a/damo/dataset/datasets/coco.py#L92-L103

![image](https://github.com/tinyvision/DAMO-YOLO/assets/15774585/df3b4527-4f46-455a-8b6c-ebb8d223b48e)

**Comment by ksv87** [comment]
![image](https://github.com/tinyvision/DAMO-YOLO/assets/15774585/65397e81-e6b6-4fd9-a2e6-b896c6ea1f0e)
