### ISSUE TITLE
ValueError: array of sample points is empty

### ISSUE THREAD

**Issue by yutao007** [tinyvision/DAMO-YOLO#24]
此时的环境跑coco_2017数据集没问题。当训练自己数据集时候出现索引错误，config文件也改为5类了。
2022-12-05 11:03:31 | INFO     | damo.apis.detector_trainer:266 - Training start...
2022-12-05 11:03:31 | ERROR    | __main__:67 - An error has been caught in function '<module>', process 'MainProcess' (5218), thread 'MainThread' (139953455899264):
Traceback (most recent call last):

> File "tools/train.py", line 67, in <module>
    main()
    └ <function main at 0x7f4882bdeb00>

  File "tools/train.py", line 63, in main
    trainer.train(args.local_rank)
    │       │     │    └ 0
    │       │     └ Namespace(config_file='configs/damoyolo_tinynasL20_T_fire_smoke_xy_calling_body.py', local_rank=0, opts=[], tea_ckpt=None, te...
    │       └ <function Trainer.train at 0x7f4875990680>
    └ <damo.apis.detector_trainer.Trainer object at 0x7f48759934d0>

  File "/home/Documents/DAMO-YOLO/damo/apis/detector_trainer.py", line 272, in train
    for data_iter, (inps, targets, ids) in enumerate(self.train_loader):
                                                     │    └ <torch.utils.data.dataloader.DataLoader object at 0x7f47e234c750>
                                                     └ <damo.apis.detector_trainer.Trainer object at 0x7f48759934d0>

  File "/home/anaconda3/envs/DAMO-YOLO/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f4882c3aef0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f47e22b3050>
  File "/home/anaconda3/envs/DAMO-YOLO/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f480e26f1d0>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f4882c3e050>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f47e22b3050>
  File "/home/anaconda3/envs/DAMO-YOLO/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7f497338cdd0>
    └ <torch._utils.ExceptionWrapper object at 0x7f480e26f1d0>
  File "/home/anaconda3/envs/DAMO-YOLO/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught ValueError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/home/anaconda3...
          │    └ <class 'ValueError'>
          └ <torch._utils.ExceptionWrapper object at 0x7f480e26f1d0>

ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/DAMO-YOLO/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/DAMO-YOLO/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/DAMO-YOLO/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/Documents/DAMO-YOLO/damo/dataset/datasets/mosaic_wrapper.py", line 308, in __getitem__
    shear=self.shear,
  File "/home/Documents/DAMO-YOLO/damo/dataset/datasets/mosaic_wrapper.py", line 142, in random_affine
    segments = resample_segments(segments)  # upsample
  File "/home/Documents/DAMO-YOLO/damo/dataset/datasets/mosaic_wrapper.py", line 29, in resample_segments
    np.interp(x, xp, s[:, i]) for i in range(2)
  File "/home/Documents/DAMO-YOLO/damo/dataset/datasets/mosaic_wrapper.py", line 29, in <listcomp>
    np.interp(x, xp, s[:, i]) for i in range(2)
  File "<__array_function__ internals>", line 6, in interp
  File "/home/anaconda3/envs/DAMO-YOLO/lib/python3.7/site-packages/numpy/lib/function_base.py", line 1439, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty

**Comment by qiqika** [comment]
@yutao007 
DAMO-YOLO-master/damo/dataset/datasets/mosaic_wrapper.py change function to " def resample_segments(segments, n=1000):
    # Up-sample an (n,2) segment
    for i, s in enumerate(segments):
        if s.shape[0]==0:    ##add line
           continue #add line"
it work for me

**Comment by yutao007** [comment]
thanks  me  too

**Comment by yutao007** [comment]
不过对于背景图片空标不能直接训练确实，不太有好。

**Comment by XianzheXu** [comment]
> 不过对于背景图片空标不能直接训练确实，不太有好。

感谢您的关注，我们正在对这个问题进行定位和分析，在下次更新版本中会修复这个问题。

**Comment by XianzheXu** [comment]
问题已经修复，增加了coco数据load时对segmentation字段的判断。没有segmentation标签的检测数据能够正常训练。
