### ISSUE TITLE
使用tools/torch_inference.py在pyharm中直接进行推理报错？

### ISSUE THREAD

**Issue by havefunheehee** [tinyvision/DAMO-YOLO#41]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

设置参数部分：
def make_parser():
    parser = argparse.ArgumentParser('damo eval')

    parser.add_argument(
        '-f',
        '--config_file',
        default=r'configs/damoyolo_tinynasL25_S.py',
        type=str,
        help='pls input your config file',
    )
    parser.add_argument('-p',
                        '--path',
                        default=r'D:\hb\DAMO-YOLO\DAMO-YOLO-master\assets\dog.jpg',
                        type=str,
                        help='path to image')
    parser.add_argument('-c',
                        '--ckpt',
                        default=r'path/to/your/damoyolo_tinynasL25_S.pth',
                        type=str,
                        help='ckpt for eval')
    parser.add_argument('--conf',
                        default=0.6,
                        type=float,
                        help='conf of visualization')

    parser.add_argument('--img_size',
                        default=640,
                        type=int,
                        help='test img size')
    return parser
运行报错：
Traceback (most recent call last):

> File "D:\hb\DAMO-YOLO\DAMO-YOLO-master\tools\torch_inference.py", line 125, in <module>
    main()
    └ <function main at 0x000001861B046DC8>

  File "D:\hb\DAMO-YOLO\DAMO-YOLO-master\tools\torch_inference.py", line 73, in main
    config = parse_config(args.config_file)
             │            │    └ 'configs/damoyolo_tinynasL25_S.py'
             │            └ Namespace(ckpt='path/to/your/damoyolo_tinynasL25_S.pth', conf=0.6, config_file='configs/damoyolo_tinynasL25_S.py', img_size=6...
             └ <function parse_config at 0x000001861B0469D8>

  File "D:\hb\DAMO-YOLO\DAMO-YOLO-master\damo\config\base.py", line 134, in parse_config
    return get_config_by_file(config_file)
           │                  └ 'configs/damoyolo_tinynasL25_S.py'
           └ <function get_config_by_file at 0x0000018619256AF8>

  File "D:\hb\DAMO-YOLO\DAMO-YOLO-master\damo\config\base.py", line 122, in get_config_by_file
    "{} doesn't contains class named 'Config'".format(config_file))
                                                      └ 'configs/damoyolo_tinynasL25_S.py'

ImportError: configs/damoyolo_tinynasL25_S.py doesn't contains class named 'Config'
请问大佬应该如何解决？
期待回复，谢谢。

**Comment by cwhgn** [comment]
可能是PYTHONPATH设置问题。可以尝试执行export PYTHONPATH=当前项目路径，试试是否能够成功运行。

**Comment by havefunheehee** [comment]
> 可能是PYTHONPATH设置问题。可以尝试执行export PYTHONPATH=当前项目路径，试试是否能够成功运行。

您好，我是在Windows10的系统下进行搭建环境与推理训练的。

**Comment by havefunheehee** [comment]
> 可能是PYTHONPATH设置问题。可以尝试执行export PYTHONPATH=当前项目路径，试试是否能够成功运行。

您好，我是在Windows10 的系统环境下搭建虚拟环境，进行推理/训练。
![微信截图_20221213152114](https://user-images.githubusercontent.com/106720376/207251756-d0bfebc6-36ec-4a1e-8612-7974b2b28ef3.png)
如图所示，我在windows的环境变量中添加了项目的文件路径为环境变量，但是使用tools/torch_inference.py在pycharm运行/推理的时候任然是出现以下报错：
![报错](https://user-images.githubusercontent.com/106720376/207252715-60475dcf-d1b3-4c71-a479-c48c4893687d.png)
我输入的参数如下图：
![输入参数](https://user-images.githubusercontent.com/106720376/207253407-28b1db4b-5c79-4ab7-be0f-0e92cd1c92ef.png)
请问我应该如何解决这个问题呢？期待您的回复！

**Comment by HYLcool** [comment]
您好，首先您可以先确认下在configs路径下是否存在该配置文件。

其次，请问您是否是在pycharm里直接右键点击tools/torch_inference.py的代码编辑页面然后点击Run运行的？

如果是的话，这样会在根目录下运行绝对路径的torch_inference.py，此时config文件的路径就不再是`configs/xxx.py`。

我们建议您在DAMO-YOLO的主目录下运行tools/torch_inference.py，如在命令行下运行：
```shell
cd <path_to_DAMO-YOLO>
python tools\torch_inference.py -f configs\xxx.py -p xxx.jpg -c xxx.pth
```
这样能够有效地避开这类路径相关的问题。

此外，注意到您没有指定ckpt路径，您可以在DAMO-YOLO代码库的[Model Zoo](https://github.com/tinyvision/DAMO-YOLO#model-zoo)中找到各个模型的torch模型地址，下载后记得指定哈~

**Comment by havefunheehee** [comment]
> 您好，首先您可以先确认下在configs路径下是否存在该配置文件。
> 
> 其次，请问您是否是在pycharm里直接右键点击tools/torch_inference.py的代码编辑页面然后点击Run运行的？
> 
> 如果是的话，这样会在根目录下运行绝对路径的torch_inference.py，此时config文件的路径就不再是。`configs/xxx.py`
> 
> 我们建议您在DAMO-YOLO的主目录下运行tools/torch_inference.py，如在命令行下运行：
> 
> ```shell
> cd <path_to_DAMO-YOLO>
> python tools\torch_inference.py -f configs\xxx.py -p xxx.jpg -c xxx.pth
> ```
> 
> 这样能够有效地避开这类路径相关的问题。
> 
> 此外，注意到您没有指定ckpt路径，您可以在DAMO-YOLO代码库的[Model Zoo](https://github.com/tinyvision/DAMO-YOLO#model-zoo)中找到各个模型的torch模型地址，下载后记得指定哈~

您好，谢谢您的回复。
按照您的指导，已解决我当前的问题，谢谢您！
